name: num_to_txt
description: A package for parsing numbers into real english words. Can convert into classic words or ordinals
version: 0.0.5
homepage: https://github.com/ryzizub/num_to_txt

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.16.8 
