name: num_to_txt
description: A package for parsing numbers into real english words. Can convert into classic words or ordinals
version: 0.0.2
homepage: https://github.com/ryzizub/num_to_txt

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  test: ^1.3.3 
